import { MapData } from './types';

const THROW_ALIAS: Record<string, string> = {
  WJT: 'setWJT',
  JT: 'setJT',
  WSJT: 'setWSJT',
  DSJT: 'setDSJT',
};

const GRENADE_ALIAS: Record<string, string> = {
  smoke: 'setSmoke',
  flash: 'setFlash',
  he: 'setHE',
  molotov: 'setMolotov',
};

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
}

function padRight(str: string, len: number): string {
  return str.padEnd(len, ' ');
}

export function generateCmdCfg(map: MapData): string {
  const mapName = sanitizeName(map.name);
  const lines: string[] = [];

  lines.push(`// AutoLineup CMD config for ${map.name}`);
  lines.push(`// Generated by CS2 AutoLineup Creator`);
  lines.push(`// ============================================================`);
  lines.push('');

  // Group lineups by tab
  const tabs = [0, 1, 2];
  tabs.forEach((tab) => {
    const tabLineups = map.lineups.filter((l) => l.tab === tab);

    // Build 8 slots for this tab
    for (let slot = 1; slot <= 8; slot++) {
      const lineup = tabLineups.find((l) => l.slot === slot);
      const tabKey = `cl_radial_radio_tab_${tab}_text_${slot}`;

      if (!lineup) {
        lines.push(`${padRight(tabKey, 40)} cmd\";autoLineupAbort;\"`);
      } else {
        const throwAlias = THROW_ALIAS[lineup.throwType] || 'setWJT';
        const grenadeAlias = GRENADE_ALIAS[lineup.grenadeType] || 'setSmoke';
        const posAlias = `${mapName}_pos_${sanitizeName(lineup.name)}_tab${tab}`;
        lines.push(
          `${padRight(tabKey, 40)} cmd\";alias pos ${padRight(posAlias + ';', 50)} ${throwAlias};\t${grenadeAlias};\tautoLineupSelectedLineup;\"`
        );
      }
    }
    lines.push('');
  });

  lines.push('//Lineups---------------------------------------------------------');
  lines.push('');

  // Generate position aliases
  const processed = new Set<string>();
  map.lineups.forEach((lineup) => {
    const posAlias = `${mapName}_pos_${sanitizeName(lineup.name)}_tab${lineup.tab}`;
    if (processed.has(posAlias)) return;
    processed.add(posAlias);

    lines.push(`// ${lineup.name} — ${lineup.description || 'no description'}`);
    lines.push(
      `alias ${posAlias} "${mapName}_${sanitizeName(lineup.name)}_x;\t${mapName}_${sanitizeName(lineup.name)}_y;\ttp_${sanitizeName(lineup.name)}"`
    );
    lines.push(
      `    alias ${mapName}_${sanitizeName(lineup.name)}_x "yaw ${lineup.yaw} 1 1;"`
    );
    lines.push(
      `    alias ${mapName}_${sanitizeName(lineup.name)}_y "pitch ${lineup.pitch} 1 1;"`
    );
    lines.push(
      `    alias tp_${sanitizeName(lineup.name)} "setpos ${lineup.posX} ${lineup.posY} ${lineup.posZ}"`
    );
    lines.push('');
  });

  return lines.join('\r\n');
}

export function generateLabelCfg(map: MapData): string {
  const lines: string[] = [];
  lines.push(`// AutoLineup LABEL config for ${map.name}`);
  lines.push(`// Generated by CS2 AutoLineup Creator`);
  lines.push('');

  const tabs = [0, 1, 2];
  tabs.forEach((tab) => {
    for (let slot = 1; slot <= 8; slot++) {
      const lineup = map.lineups.find((l) => l.tab === tab && l.slot === slot);
      const tabKey = `cl_radial_radio_tab_${tab}_text_${slot}`;
      if (lineup) {
        lines.push(`${padRight(tabKey, 40)} "${lineup.name}"`);
      } else {
        lines.push(`${padRight(tabKey, 40)} ""`);
      }
    }
    lines.push('');
  });

  return lines.join('\r\n');
}

export function generateReadme(map: MapData): string {
  const lines: string[] = [];
  lines.push(`# ${map.name} Lineup List`);
  lines.push('');
  lines.push('| Tab | Slot | Name | Grenade | Throw | Description |');
  lines.push('|-----|------|------|---------|-------|-------------|');

  map.lineups
    .sort((a, b) => a.tab - b.tab || a.slot - b.slot)
    .forEach((l) => {
      lines.push(
        `| ${l.tab} | ${l.slot} | ${l.name} | ${l.grenadeType} | ${l.throwType} | ${l.description || ''} |`
      );
    });

  return lines.join('\n');
}

export function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
